name: default
channels:
- conda-forge
- nvidia
- nodefaults
dependencies:
- rdkit ==2024.3.5
- python >=3.11
- pip
- pip:
  - -e .
  - absl-py
  - chex
  - dm-haiku==0.0.13
  - dm-tree
  - jax[cuda12]==0.4.34
  - jax-triton==0.2.0
  - jaxtyping
  - numpy
  - rdkit==2024.3.5
  - triton==3.1.0
  - tqdm
  - zstandard

