name: AF3
channels:
- conda-forge
- bioconda
- nvidia
- nodefaults
dependencies:
- hmmer ==3.4
- rdkit ==2024.3.5
- git >=2.47.0,<3
- wget >=1.21.4,<2
- pip >=24.3.1,<25
- curl >=8.10.1,<9
- zstd >=1.5.6,<2
- cmake >=3.30.5,<4
- cuda ==12.6
- cuda-toolkit ==12.6
- python >=3.11
- pip
- pip:
  - -e .
  - absl-py
  - chex
  - dm-haiku==0.0.13
  - dm-tree
  - jax[cuda12]==0.4.34
  - jax-triton==0.2.0
  - jaxtyping
  - numpy
  - triton==3.1.0
  - tqdm
  - zstandard
